### ISSUE TITLE
How to exclude/ignore specific errors ? Error: Request failed with status code 401

### ISSUE THREAD

**Issue by Rolanddoda** [Zevran/vue-rollbar#11]
When the user is unauthenticated and tries to make requests he gets 401 (Unauthenticated) error.

However this is not an error of course and I was looking if there is any way to exclude such errors requests.

I found something [here in the docs](https://docs.rollbar.com/docs/filter-or-ignore-errors-from-bots#section-filtering-client-side) which I am not sure yet how to implement, but it says

> Some of our other libraries don't implement checkIgnore yet.

And in vue.js docs I can't see it so maybe it's not implemented there.

In there any way I can exclude/ignore specific errors ?

**Comment by gaelreyrol** [comment]
This package relies on Rollback javascript library so you only need to refer to their documentation.
