### ISSUE TITLE
this.rollbar undefined in component

### ISSUE THREAD

**Issue by Elbone** [Zevran/vue-rollbar#5]
Hi @Zevran 
Just a heads up that in my build of Vue (^2.3.3) I ran into an issue where the this.rollbar was not available on the component. I fixed it by instantiating Rollbar as a mixin like so:
````
var Rollbar = require("rollbar");
module.exports = function (Vue, options) {
  Vue.mixin({
    created: function () {
      this.$rollbar = new Rollbar(options);
    }
  })
}
````
Not sure of the root cause or if that's the appropriate solution but it worked for me.

**Comment by gaelreyrol** [comment]
Hi @Elbone,

Thanks for having reported the error, this should be fixed with #4 pr !
