### ISSUE TITLE
Uncaught TypeError: Rollbar is not a constructor

### ISSUE THREAD

**Issue by gustavogf** [Zevran/vue-rollbar#7]
Sample code:

```javascript
import Rollbar from 'vue-rollbar';

export default {
  install(Vue, params = {}) {
    Vue.use(Rollbar, {
      accessToken: '[token]',
      captureUncaught: true,
      captureUnhandledRejections: true,
      enabled: true,
      source_map_enabled: false,
      environment: 'production',
    });
...
```

This error is triggered on the following line in vue-rollbar: https://github.com/Zevran/vue-rollbar/blob/develop/index.js#L5

**Comment by gaelreyrol** [comment]
Hi !
Could you show me how do you instanciate your vue app ?

**Comment by gustavogf** [comment]
> Hi !
> Could you show me how do you instanciate your vue app ?

```javascript
function initVueApp(config) {
  Vue.use(plugin, config);

  window.vueApp = new Vue({
    el: '#app',
    template: '<dashboard />',
  });
}
```

`plugin` is the file that contains the code quoted above.

**Comment by gaelreyrol** [comment]
Are you sure you can cycle `Vue.use` by having a plugin within a plugin ?

**Comment by gustavogf** [comment]
Yes, Vue Router is configured this way

**Comment by gaelreyrol** [comment]
Have you tried to instanciate it normally ? Just to check if the error occurs even in the standard way.
